
DROP DATABASE if exists EKART;
CREATE DATABASE EKART;
USE EKART;


CREATE TABLE EK_CUSTOMER(
	EMAIL_ID VARCHAR(50),
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(70) NOT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
	constraint EK_CUSTOMER_EMAIL_ID_PK primary key ( EMAIL_ID )
);

INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('tom@infosys.com', 'Tom', 'Tom@123', '7886189067');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('harry@infosys.com', 'Harry', 'Harry@123', '7687156584');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('john@infosys.com', 'John', 'John@123', '8478116714');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('sara@infosys.com', 'Sara', 'Sara@123', '8900100511');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('mariya@infosys.com', 'Mariya', 'Mariya@123', '7578116427');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('james@infosys.com', 'James', 'James@123', '8032179231');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('steve@infosys.com', 'Steve', 'Steve@123', '7730157577');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('punya@infosys.com', 'Punya', 'Punya@123', '8064153936');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('animesh@infosys.com', 'Animesh', 'Animesh@123', '7335189166');
INSERT INTO EK_CUSTOMER (EMAIL_ID, NAME, PASSWORD, PHONE_NUMBER) VALUES ('rakesh@infosys.com', 'Rakesh', 'Rakesh@123', '7411164668');

commit;